name: Next

on:
  push:
    branches: [next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'next'
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@master
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          echo "IdentityFile ~/.ssh/server_key" >> ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/server_key
          chmod 400 ~/.ssh/server_key
          ssh-keyscan reinisch.io >> ~/.ssh/known_hosts

      - uses: actions/download-artifact@master
        with:
          name: build
          path: ./dist

      - name: Upload build files
        run: rsync -rv --delete ./dist/ ubuntu@reinisch.io:/home/ubuntu/www/home-next
